version: "3.7"

services:
  app:
    # name image
    image: '${IMAGE}'
    # setup for build image (path for dockerfile e target in docker file [not mandatory])
    networks:
      - proxy
    build:
      # path Dockerfile
      context: ./
      # Target use in dockerfile with multiple setup (example: local, prod)
      target: '${TARGET}'
    # entrypoint: bash -c '${COMMAND}'
    ports:
      - '7000:7000'
    # depends_on:
    #   - postgresbase
    # One of the main advantages of using Docker volumes
    # is the possibility of changing the content/configuration
    # of a container without the need to recreate it.
    # volumes:
    #  - ./backend/src:/app/backend/src  

networks:
  proxy:
    external: true
